### ISSUE TITLE
Bluetooth keyboard...

### ISSUE THREAD

**Issue by darkermatter** [snyball/Hawck#15]
Hi,

is there any way of making this work with a bluetooth keyboard?

Thanks!

**Comment by snyball** [comment]
Compile lsinput from Hawck and provide the output of the following command:
```sh
$ lsinput
```
This should print out something like this:
```
event18: Hawck virtual keyboard device
event8: ThinkPad Extra Buttons
    by-path: platform-thinkpad_acpi-event
event7: TPPS/2 IBM TrackPoint
    by-path: platform-i8042-serio-2-event-mouse
event6: SynPS/2 Synaptics TouchPad
    by-path: platform-i8042-serio-1-event-mouse
event3: AT Translated Set 2 keyboard
    by-path: platform-i8042-serio-0-event-kbd
event2: Power Button
event1: Sleep Button
event0: Lid Switch
```
In my case, the keyboard is "AT Translated Set 2 keyboard", so my keyboard device file is `/dev/input/event3`

You then want to find out which file in `/dev/input/` your bluetooth keyboard corresponds to, and to run `hawck-inputd --kbd-device $your_bluetooth_kbd_device`.

**Comment by darkermatter** [comment]
Hi Jonas!

I got the following error trying to compile lsinput:

```
$ gcc lsinput.cpp 
lsinput.cpp:47:10: fatal error: SystemError.hpp: No such file or directory
   47 | #include "SystemError.hpp"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

I found the device with another method  and got the UI up and running but the ```Keymap``` button
 on the settings tab  has no entries.

![Screenshot from 2019-09-30 16-42-21](https://user-images.githubusercontent.com/5037324/65889295-53ff7080-e3a1-11e9-9f0d-7fcb3846da35.png)

I'm running on Fedora 31.

Thanks!

**Comment by snyball** [comment]
Hmm, the UI looks for keymaps in these two directories:
- `/usr/share/keymaps`
- `/usr/share/kbd/keymaps`

On Debian based systems the `console-data` package is required to get the `/usr/share/keymaps` directory, I don't know what the setup looks like for Fedora, it would help if you could poke around with something like:
```
$ find / -name "*.kmap"
$ find / -name "*.map"
$ find / -name "*.kmap.gz"
$ find / -name "*.map.gz"
```

As for compiling lsinput, you can do this from the `src/tools` directory:
```
$ g++ -std=c++17 lsinput.cpp -I.. -o lsinput
$ sudo ./lsinput
```
You could also do it through the build system, the install script should compile lsinput and put it inside `build/src/lsinput`.

**Comment by darkermatter** [comment]
Hi Jonas!

On my Fedora machine, it appears the keymaps are in ```/usr/lib/kbd/keymaps```. For now, I just copied the directory into ```/usr/share``` but when I click the button, nothing shows up.

When I activate ```example.hwk``` I get a notification saying "Require authentication as hawck-input".
I am a member of the ```hawck-input-share``` group.

I now have ```lsinput``` compiled, thanks!

**Comment by snyball** [comment]
The `hawck-input-share` group is a bridge group for communication via UNIX domain sockets, as of now you still need to authenticate in order to install key permission files (required for each script.)

The UI is a bit unstable I'm afraid, getting authentication prompts to reliably appear on different distributions has been an issue, you're supposed to get a polkit password entry prompt in this case (I'll have to do some testing on Fedora to see why it isn't appearing.)

The easiest way to get things up and running to test some scripts would be for you to just bypass the UI for now:

1. Make sure Hawck is properly installed, e.g you should have the `~/.local/share/hawck` directory and the `/usr/share/hawck` directories set up.
2. Enable "unsafe mode", which sidesteps the need for authentication:
```
## __UNSAFE_MODE.csv can also be found in hawck-master/bin
$ sudo cp /usr/share/hawck/keys/__UNSAFE_MODE.csv /var/lib/hawck-input/keys/
$ sudo chown hawck-input:hawck-input /var/lib/hawck-input/keys/__UNSAFE_MODE.csv
$ sudo chmod 0644 /var/lib/hawck-input/keys/__UNSAFE_MODE.csv
```
3. Create a script inside `~/.local/share/hawck/scripts`
```
$ nano ~/.local/share/hawck/scripts/my_script.lua
$ chmod 0744 ~/.local/share/hawck/scripts/my_script.lua
```
4. Start up `hawck-inputd` and `hawck-macrod`
  - `macrod` will automatically reload the script when you save it after a subsequent edit, so you don't need to restart `macrod` when changing the scripts.
5. The Hawck daemons log their errors to syslog, so you can check for errors with `journalctl -n 10000 | grep -E "hawck-(inputd|macrod)"`
6. You'll also have to edit the `~/.local/share/hawck/cfg.lua` file, here's what mine looks like:
```
local config = {
  disable_on_err = false,
  eval_repeat = true,
  notify_on_err = true,
  -- This is the line you want to change, `macrod` will look for a file matching "$keymap.kmap" or
  -- "$keymap.kmap.gz", or "$keymap.map", etc in `$the_keymap_directory`
  keymap = "no-latin1",
  eval_keyup = true,
  disabled = false,
  eval_keydown = true,
}
return config
```

Here's an example script (note the lack of an `=>` operator, the UI automates the process of translating `a => b` into `__match[a] = b`, but it can be tedious to run the scripts manually):
```lua
require "init"

__match[key "Caps" ] = replace "Escape"

__match[mode("Programming mode", -up + key "F7") + down ] = MatchScope.new(function (__match)
  __match[shift ] = MatchScope.new(function (__match)
    __match[key "ø" ] = insert "["
    __match[key "æ" ] = insert "]"
  end)
  __match[key "ø" ] = insert "{"
  __match[key "æ" ] = insert "}"
end)

__match[key "F7" ] = off
```

That got a bit long, but hopefully it solves your problem.

I'll have to add the Fedora keymap location to the list of possible keymap locations.
