### ISSUE TITLE
Unable to install AUR on Archlinux

### ISSUE THREAD

**Issue by ejemba** [snyball/Hawck#18]
Hi , I cannot install hawck-git AUR 
I have at the end of the compilation process
```
erreur : la validation de la transaction a échoué (conflit de fichiers)
hawck-git : /usr/local/share/man est déjà présent dans le système de fichiers (appartenant à filesystem)
Des erreurs se sont produites, aucun paquet n’a été mis à jour.
```
in english something like 
"/usr/local/share/man is already present on the file system (belonging to filesystem)"

**Comment by snyball** [comment]
Yeah I was actually struggling with this myself.

It seems like `/usr/local/share/man` is symlinked to `/usr/share/man`, which is causing the problem. On my system this wasn't the case, but I ran into the issue as soon as I tried running the build in a VM.

A simple workaround
```sh
$ ls -l /usr/local/share/man
.... /usr/local/share/man -> (something, but probably /usr/share/man)
$ # Remove the link temporarily
$ sudo unlink /usr/local/share/man
$ # run install here
...
$ # Restore the symbolic link (we might break something else if we don't restore it)
$ # Make sure to not misspell that path, which would accidentally remove all your manpages!
$ sudo rm -r /usr/local/share/man 
$ sudo ln -s /usr/share/man /usr/local/share/man
```

This should get hawck to install, but will not install the man pages, you can read them in markdown/HTML format in the GitHub repo inside the `docs` directory.

What I plan to do in order to resolve it is to just make `meson` install man pages to `/usr/share/man` instead (I just haven't gotten around to doing it yet.)

I'll update this issue when I manage to fix that.

**Comment by calimeroteknik** [comment]
The arch linux packaging guidelines explicitly prohibit installing in /usr/local, and namcap notices :
```sh
$ namcap hawck-git-20200303-1-x86_64.pkg.tar.gz 
hawck-git E: ELF file ('usr/local/bin/hawck-inputd') outside of a valid path.
hawck-git E: ELF file ('usr/local/bin/hawck-macrod') outside of a valid path.
hawck-git W: File (usr/local/) exists in a non-standard directory.
hawck-git W: File (usr/local/bin/) exists in a non-standard directory.
hawck-git W: File (usr/local/bin/hawck-add) exists in a non-standard directory.
hawck-git W: File (usr/local/bin/hawck-inputd) exists in a non-standard directory.
hawck-git W: File (usr/local/bin/hawck-macrod) exists in a non-standard directory.
hawck-git W: File (usr/local/bin/hwk2lua) exists in a non-standard directory.
hawck-git W: File (usr/local/share/) exists in a non-standard directory.
hawck-git W: File (usr/local/share/man/) exists in a non-standard directory.
hawck-git W: File (usr/local/share/man/man1/) exists in a non-standard directory.
hawck-git W: File (usr/local/share/man/man1/hawck-inputd.1.gz) exists in a non-standard directory.
hawck-git W: File (usr/local/share/man/man1/hawck-macrod.1.gz) exists in a non-standard directory.
hawck-git W: Potential non-FHS man page (usr/local/share/man/man1/hawck-inputd.1.gz) found.
hawck-git W: Potential non-FHS man page (usr/local/share/man/man1/hawck-macrod.1.gz) found.
hawck-git E: Missing custom license directory (usr/share/licenses/hawck-git)
hawck-git W: File etc/systemd/system/hawck-inputd.service should be in /usr/lib/systemd/system/
hawck-git W: Dependency hicolor-icon-theme detected but optional (needed for hicolor theme hierarchy)
hawck-git W: Dependency included and not needed ('kbd')
```
The PKGBUILD on AUR needs fixing, it is not a good idea to install package files in /usr/local because it is reserved, in theory, for quick&sloppy installs by the system administrator, and can be erased at any moment, which would be inconsistent with managing the files with a package manager.

**Comment by snyball** [comment]
@calimeroteknik, thanks for the heads-up. I'll move everything out of `local` and into `bin`/`man` proper.

**Comment by snyball** [comment]
Should be fixed by now, `namcap` reports: (thanks @calimeroteknik, didn't know about this tool.)
```
hawck-git E: Missing custom license directory (usr/share/licenses/hawck-git)
hawck-git W: Dependency included and not needed ('kbd')
```

It still complains about a missing license, as it is being installed to `/usr/share/licenses/hawck/LICENSE`, I don't think I want a separate `/usr/share/licenses/hawck-git`.

I'm pretty sure `kbd` is needed, but I'll do some VM testing to know for sure.

Let me know if this works for you now @ejemba.

**Comment by ejemba** [comment]
@snyball the install ran smoothly , thank you for your action. 
If I have an issue actually running I'll open a new issue.

@calimeroteknik thank you for your review !
