### ISSUE TITLE
Support multipurpose keys with time threshold

### ISSUE THREAD

**Issue by dit7ya** [snyball/Hawck#29]
Support modifying any key as a modifier as well as normal as in [mooz/xkeysnail: Yet another keyboard remapping tool for X environment](https://github.com/mooz/xkeysnail/).

Another option that would be crucial here is to define a time threshold - when I press a key that is defined as both a modifier and a regular one, activate it as a modifier only when it is held down for longer than the threshold time. This is important otherwise you end up with wrong inputs if you are a type reasonably fast.

**Comment by snyball** [comment]
This has been asked before: https://github.com/snyball/Hawck/issues/8

It's possible but because of an unimplemented feature (passthrough scripts that can be pipelined,) the solution is a bit iffy for now.

```lua
-- Note: because of how this is implemented, it needs to be put in a separate script,
-- and needs to be the first script to run.
-- It also requires you to enable unsafe mode, as it needs to receive all keyboard input
-- to work.
caps_down = false
caps_as_ctrl = false
up + key "caps" => function ()
  caps_down = false
  if not caps_as_ctrl then
    kbd:press("caps")
  else
    kbd:up("control")
  end
  caps_as_ctrl = false
end

down + key "caps" => function ()
  caps_down = true
  caps_as_ctrl = false
end

down => {
  -- ... put the rest of your bindings here, inside down {}, but before any{} ...
  any => function ()
    if caps_down and not caps_as_ctrl then
      kbd:down("control")
      caps_as_ctrl = true
    end
    kbd:echo()
  end
```

Another feature standing in the way of this being shipped with hawck by default, is inputd scripts, i.e scripts that run inside a sandbox, so that they don't need whitelisting of keys.

But it should work, also note that this solution doesn't use any timing (that's left as an exercise to the reader.)

**Comment by snyball** [comment]
Reopening this so you can tell me whether or not that code works, or if you were able to improve on it with the timing features you needed.
